#!/bin/sh
#
# Run ffmpeg in a container
#
# This script will attempt to mirror the host paths by using volumes for the
# following paths:
#   * $(pwd)
#   * $(dirname $GOPATH) if it's set
#
# You can add additional volumes (or any docker run options) using
# the $DOCKER_RUN_OPTIONS environment variable.
#


set -e

SWD=$(readlink -f "$0" | xargs dirname)


export DOCKER_RUN_OPTIONS="$DOCKER_RUN_OPTIONS --entrypoint ffprobe"
exec $SWD/ffmpeg $@
