#! /bin/sh

IMAGE="tor:local"
SWD=$(readlink -f "$0" | xargs dirname)

tor_port=$(docker ps -q -f "ancestor=$IMAGE" | xargs docker port 2> /dev/null | cut -d ':' -f 2) 

if [ -z $tor_port  ]; then
	$SWD/tor > /dev/null &
	while [ -z $tor_port ]; do
		sleep 1;
		tor_port=$(docker ps -q -f "ancestor=$IMAGE" | xargs -r docker port | cut -d ':' -f 2) 
	done
fi	

cat << EOF
Tor is listening on: socks5://localhost:$tor_port
EOF

export http_proxy=socks5://localhost:$tor_port
export https_proxy=socks5://localhost:$tor_port
exec $@ 
